name: Publish Docker image
on:
  workflow_dispatch:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get version
        id: get-version
        run: echo "::set-output name=version::`echo ${{ github.ref }} | grep -Eo -m1 'v(.+)$' -`"
      - name: Set up QEMU
        id: qemu
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
      - name: Setup Docker Buildx
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        if: ${{ steps.get-version.outputs.version }}
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: ${{ steps.qemu.outputs.platforms }}
          push: true
          tags: |
            paradisi/motion-onvif-events:latest
            paradisi/motion-onvif-events:${{ steps.get-version.outputs.version }}
